[package]
authors = [
  "siwilizhao <siwilizhao@gmail.com>",
] 
categories = [
  "text-processing",
  "multimedia",
  "parser-implementations",
] 
description = "Subtitler is a library for parsing and generating subtitles" 
documentation = "https://docs.rs/subtitler" 
edition = "2021" 
keywords = ["subtitler", "vtt", "srt", "subtitle", "sub-title"] 
license = "Apache-2.0" 
name = "subtitler" 
publish = true # no accidents while in dev
readme = "README.md" 
repository = "https://github.com/subtitle-rs/subtitler" 
version = "0.0.1" 

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*", #"build.rs",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"
thiserror = "^2.0"
tokio = {version = "^1.42", features = ["full"]}
tracing = "^0.1"
regex = "^1.11"

[dev-dependencies]

[features]
default = []

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true

[examples]
